server:
  port: ${PORT:8080} # Puerto único donde correrá el punto de entrada global

authorization:
  jwt:
    secret: ${AUTHORIZATION_JWT_SECRET}

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # Permitirá que el Frontend en Angular se conecte sin errores de CORS
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # RUTA 1: IAM SERVICE (Autenticación)
        - id: iam-service
          uri: ${IAM_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/authentication/**

        # RUTA 2: PROFILE SERVICE (Perfiles)
        - id: profile-service
          uri: ${PROFILE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/profiles/**
          filters:
            - AuthenticationFilter

        # RUTA 3: ORGANIZATION SERVICE (Terrenos/Parcelas)
        - id: organization-service
          uri: ${ORGANIZATION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/plots/**,/api/v1/organizations/**,/api/v1/plant-types/**
          filters:
            - AuthenticationFilter

        # RUTA 4: SUBSCRIPTION SERVICE
        - id: subscription-service
          uri: ${SUBSCRIPTION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/subscriptions/**
          filters:
            - AuthenticationFilter
        # RUTA 5: MONITORING AND CONTROL SERVICE
        - id: monitoring-control-service
          uri: ${MONITORING_CONTROL_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/environment-readings/**,/api/v1/plant-sampling-sessions/**,/api/v1/tasks/**
          filters:
            - AuthenticationFilter
        # RUTA 6: REPORTS SERVICE
        - id: reports-service
          uri: ${REPORTS_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/v1/reports/**, /api/v1/organizations/*/plots/*/reports
          filters:
            - AuthenticationFilter